server:
  port: 18190
  servlet:
    context-path: /v1/xxl-job-admin

management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

### resources
spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  ### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iot_job_mgmt?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: iot_platform
    password: 8a4b041e
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000

  mail:
    host: smtp.qq.com
    port: 25
    username: XX@XX.COM
    from: xx@xx.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

xxl:
  job:
    accessToken: iot_xxl_job_access_token
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml